### ISSUE TITLE
error help pls

### ISSUE THREAD

**Issue by HsounaZinoubi** [matiasinsaurralde/evilredis#2]
-- Target : x.x.x.x ... evilness level 3 

/usr/local/lib/node_modules/evilredis/index.js:37
hosts.forEach( function( host, index ) {
     ^

TypeError: Cannot read property 'forEach' of null
    at Object.<anonymous> (/usr/local/lib/node_modules/evilredis/index.js:37:6)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by matiasinsaurralde** [comment]
What arguments are you using? (don't worry, you can mask the IP)

**Comment by HsounaZinoubi** [comment]
evilredis x.x.x.x 3 /root/id_rsa.pub

**Comment by matiasinsaurralde** [comment]
You need to specify the subnet mask, like:
`evilredis 192.168.0.5/32`
or
`evilredis 192.168.0.0/24`

Regards

**Comment by HsounaZinoubi** [comment]
i m trying to attack single ip is this possible ?

**Comment by matiasinsaurralde** [comment]
Yes, you should use `/32`, so:

`evilredis 192.168.0.1/32`
